Origin/gallery   masonry
JOOOEG123/stip-demo pull request #17
Opened 2022-06-14 19:52 UTC by dangan114

Create masonry columns (collage) for the gallery page.

2022-06-14 21:16 UTC, JOOOEG123 requested changes
Looks Good. You need to rebase. :)

2022-06-14 21:16 UTC, JOOOEG123 requested changes
rebase. Fetch current branch.

2022-06-15 00:18 UTC, JOOOEG123 commented
I rebased it.

2022-06-15 00:18 UTC, yzhang54 approved these changes

2022-06-15 00:18 UTC, merged