Browse/search result design
JOOOEG123/stip-demo pull request #37
Opened 2022-06-21 13:18 UTC by yzhang54

2022-06-21 14:29 UTC, JOOOEG123 commented on src/app/pages/browse/browse-archive/browse-archive.component.ts
> +    });
you are close to the approach I am going with.

2022-06-21 14:33 UTC, JOOOEG123 commented on src/app/pages/browse/main-browse/main-browse.component.ts
> +    var search_layout = document.getElementsByName("searchLayout");
You don't get value like this in a modern framework.

2022-06-21 14:39 UTC, JOOOEG123 requested changes

2022-06-21 14:39 UTC, JOOOEG123 commented on src/app/pages/browse/main-browse/main-browse.component.ts
> +    var search_layout = document.getElementsByName("searchLayout");
you can just use variable **curView**.

2022-06-22 13:05 UTC, weilonp approved these changes

2022-06-26 18:49 UTC, JOOOEG123 requested changes
Please fix the issue in your comment before you work on a different page or functionality. Reason: It is much easy and less confusing if you focus one one thing at a time.

2022-06-26 18:49 UTC, JOOOEG123 commented on src/app/pages/browse/memoir/memoir.component.html
> +  />
move create a svg file for this and use img. Reson: makes it easy to maintain all images

2022-06-26 18:49 UTC, JOOOEG123 commented on src/app/pages/browse/share/share.component.html
> +            </span>
move it to svg

2022-06-27 14:03 UTC, yzhang54 commented on src/app/pages/browse/memoir/memoir.component.html
> +  />
@weilonp Hi, could you please work on this as you did this part?

2022-06-27 15:01 UTC, merged