Wp week4
JOOOEG123/stip-demo pull request #43
Opened 2022-06-22 19:34 UTC by weilonp

2022-06-22 19:38 UTC, weilonp commented
Upload page layout and about page reponsiveness

2022-06-24 20:31 UTC, JOOOEG123 requested changes
check comments a lot of your issues are minor, however it could cause a big issue related to usability.

2022-06-24 20:31 UTC, JOOOEG123 commented on src/app/pages/account/account.component.html
> +      <!-- enter name form -->
Good way to make it responsive. Nicely done.

2022-06-24 20:31 UTC, JOOOEG123 commented on src/app/pages/account/account.component.html
> +          type="text"
remove all inline styling. It causes headache later. and use can use pb-2 or pb-3 in this case.

2022-06-24 20:31 UTC, JOOOEG123 commented on src/app/pages/account/account.component.html
> +        <select
check comment above. I will stop adding comment related to padding. :)

2022-06-24 20:31 UTC, JOOOEG123 commented on src/app/pages/account/account.component.html
> +        <label for="floatingSelect">Chinese ethnic group</label>
this will be type ahead. Check Yule filter component

2022-06-24 20:31 UTC, JOOOEG123 commented on src/app/pages/account/account.component.html
> +      </div>
you added for="" to the label however it is not linked to any ID. Check all you forms.

2022-06-24 20:31 UTC, JOOOEG123 commented on src/app/pages/account/account.component.html
> +      style="height: 200px"
use row="3" or any number you want

2022-06-27 14:18 UTC, closed without merging