Search bar and search filter
JOOOEG123/stip-demo pull request #58
Opened 2022-07-02 16:28 UTC by yzhang54

2022-07-02 16:50 UTC, JOOOEG123 requested changes

2022-07-02 16:50 UTC, JOOOEG123 commented on src/app/pages/browse/browse-search-filter/browse-search-filter.component.html
> +
yep. Good work

2022-07-02 16:50 UTC, JOOOEG123 commented on src/app/pages/browse/browse-search-filter/browse-search-filter.component.scss
> +}
I dont know why you need this. 
use this instead. 
**.calender {
display: none !important;
}**

2022-07-02 16:50 UTC, JOOOEG123 commented on src/app/pages/browse/browse-search-filter/jquery.js
> +});
what is this for? You might have get this js code from somewhere. you could just use ts also.

2022-07-02 16:50 UTC, JOOOEG123 commented on src/app/pages/browse/browse-search-filter/browse-search-filter.component.html
>              </option>
run prettier formatting

2022-07-02 16:50 UTC, JOOOEG123 commented on src/app/core/pipes/update-rows-pipe.pipe.ts
> +
Curious: why did you add a white space?

2022-07-02 16:50 UTC, JOOOEG123 commented on src/app/pages/browse/main-browse/main-browse.component.ts
> +
you dont need to add white space. This is why I encourage you to run prettier.

2022-07-02 17:00 UTC, yzhang54 commented on src/app/pages/browse/browse-search-filter/browse-search-filter.component.scss
> +}
I tried this before, but this would hide both calendars.

2022-07-02 17:03 UTC, yzhang54 commented on src/app/pages/browse/browse-search-filter/jquery.js
> +});
Lol, pls ignore this. I deleted this code. (It was just for experimental, not sure why it is on git.)

2022-07-02 17:05 UTC, yzhang54 commented on src/app/core/pipes/update-rows-pipe.pipe.ts
> +
Was trying to add some IDs for the search research display, so was trying to add some code for pipes to modify the DB variable array structure.

2022-07-05 17:20 UTC, weilonp approved these changes

2022-07-06 14:51 UTC, closed without merging