complete partial functionaties of browsing page and set up some angul…
JOOOEG123/stip-demo pull request #8
Opened 2022-06-07 22:37 UTC by yzhang54

…ar config

2022-06-07 22:39 UTC, yzhang54 commented
Don't worry about the CSS for now; I will add more style later.

2022-06-08 03:04 UTC, JOOOEG123 requested changes
You made a lot of good changes. I think you unerstand more about angular now.  Just a reminder we dont use material we use boostrap and ngx bootstrap. It has similar function as material and have all the scss class you will need. Let meet tomorrow. :) Great Job on creating you fire Angular PR.

2022-06-08 03:04 UTC, JOOOEG123 commented on src/app/pages/browse/browse.component.ts
> +    {value: '26', viewValue: 'Sui'},
Nice, this looks. We would use this.

2022-06-08 03:04 UTC, JOOOEG123 commented on src/styles.scss
> +
we use bootstrap and not material ui

2022-06-08 03:04 UTC, JOOOEG123 commented on tsconfig.app.json
> +    "paths": { "@angular/*": [ "../node_modules/@angular/*" ] }
making changes here could break the application.

2022-06-08 03:04 UTC, JOOOEG123 commented on src/app/pages/browse/browse.component.ts
> +  }
This is correct, I will show you possible next step.

2022-06-08 13:19 UTC, yzhang54 commented on src/app/pages/browse/browse.component.html
> +        <section class="status-section">
Could you pls clarify the reasons why we switched? And would it be possible we combine both of them?

2022-06-08 13:19 UTC, yzhang54 commented on src/app/pages/browse/browse.component.html
> +
Will fix later, thanks.

2022-06-09 19:23 UTC, closed without merging