complete account contribution and edit page and upload clean up
JOOOEG123/stip-demo pull request #85
Opened 2022-07-17 03:08 UTC by JOOOEG123

2022-07-17 15:59 UTC, yzhang54 requested changes

2022-07-17 15:59 UTC, yzhang54 commented on src/app/core/constants/group.constants.ts
> +  'Zhuang',
I think "Han" is missing from this array. You may check other groups in detail via this link. https://en.wikipedia.org/wiki/List_of_ethnic_groups_in_China Hope this can be helpful.

2022-07-17 15:59 UTC, yzhang54 commented on src/app/pages/homepage/homepage.component.html
> -          <input type="search" class="form-control rounded-end rounded-pill" placeholder="Search for Archives"
We will need these codes. Please grab the latest. :)

2022-07-17 16:02 UTC, JOOOEG123 commented on src/app/pages/homepage/homepage.component.html
> -          <input type="search" class="form-control rounded-end rounded-pill" placeholder="Search for Archives"
Check it again the code is still there. I ran prettier. Please check again and verify.

2022-07-17 16:02 UTC, JOOOEG123 commented on src/app/core/constants/group.constants.ts
> +  'Zhuang',
I will add it when I get home.

2022-07-17 16:04 UTC, JOOOEG123 commented on src/app/pages/homepage/homepage.component.html
> -          <input type="search" class="form-control rounded-end rounded-pill" placeholder="Search for Archives"
Check the code properly you will notice the code is still there.

2022-07-17 16:04 UTC, JOOOEG123 commented on src/app/core/constants/group.constants.ts
> +  'Zhuang',
Or you can update it. I am currently out.

2022-07-17 16:19 UTC, JOOOEG123 commented on src/app/core/constants/group.constants.ts
> +  'Zhuang',
Added

2022-07-18 03:01 UTC, JOOOEG123 commented
@yzhang54 I have fix the ethnic list.  Merging PR let me know if anything changes.

2022-07-18 03:01 UTC, merged